entrada = int ('Digite algo ')
print (f'Tipo primario: {type(entrada)}')
print (f'É numerico: {entrada.isnumeric()}')
print (f'É alfabetico: {entrada.isalpha()}')
print (f'Esta tudo em maiusculo?: {entrada.isupper()}')
print (f'Esta tudo em mainusculo?: {entrada.islower()}')
print (f'É um decimal?: {entrada.isdecimal()}')